language: node_js

node_js:
  - '11'
  - '10'
  - '9'
  - '8'

before_install:
  - nvm install-latest-npm

install:
  - npm install --only=dev

script:
  - npm run test
  - npm run lint

cache:
  directories:
    - node_modules

  sudo: false
